# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 03:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rovigridschedule',
            name='service_id',
        ),
        migrations.AddField(
            model_name='rovigridschedule',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guide.RoviListings'),
        ),
    ]
