# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_auto_20160320_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rovilistings',
            name='postal_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
