# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_auto_20160320_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='rovigridschedule',
            name='postal_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
