# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_rovigridschedule_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='rovilistings',
            name='service_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
