# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 01:39
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0005_rovilistings_service_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSigns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.TextField()),
                ('network_affilitation', models.TextField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
    ]
