# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0006_callsigns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rovilistings',
            name='service_id',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
