# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 00:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0008_auto_20160330_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callsigns',
            old_name='network_affilitation',
            new_name='network_affiliation',
        ),
    ]
