# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-23 15:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0010_roviprogramimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='rovigridschedule',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 23, 15, 19, 40, 859229, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
