# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 04:12
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Channel'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='is_on_sling',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='package',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={'content': '', 'hardware': '', 'services': ''}, null=True),
        ),
    ]
