# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20160225_0412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='channel',
        ),
        migrations.AddField(
            model_name='content',
            name='channel',
            field=models.ManyToManyField(blank=True, null=True, to='server.Channel'),
        ),
    ]
