# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20160225_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='on_netflix',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='content',
            name='channel',
            field=models.ManyToManyField(blank=True, to='server.Channel'),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
