# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 03:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20160725_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL),
        ),
    ]
