# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 21:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20160228_2108'),
        ('server', '0004_auto_20160228_2128'),
    ]

    operations = [
    ]
