# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-30 02:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='device_id',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
