# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-09 01:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_auto_20160730_0249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popularity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.1)),
                ('date_created', models.DateField(default=datetime.datetime(2016, 8, 9, 1, 0, 28, 955309, tzinfo=utc))),
            ],
            options={
                'managed': False,
                'get_latest_by': 'date_created',
                'db_table': 'popularity_popularity',
            },
        ),
    ]
