# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_auto_20160522_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='channels_last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
