# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-09 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='curr_pop_score',
            field=models.FloatField(default=0.1),
        ),
    ]
